### ISSUE TITLE
No error reporting on first connection

### ISSUE THREAD

**Issue by lypnol** [Succo/twilight#3]
https://github.com/Succo/twilight/blob/cf32a3146f25b3252a1d5acb518aeade84444a00/server.go#L85
Hi there!  First thank you for this amazing tool,  
I noticed there were no error reporting in that case, that would probably be because `fmt.Errorf` doesn't print the error it just creates an `error` instance

**Comment by Succo** [comment]
Good catch.

I couldn't bother making an error channel and better error handling so I just made the application panic.
